### ISSUE TITLE
Issue upon login to admin control panel

### ISSUE THREAD

**Issue by tantuohy** [manishjoy/customer-ajax-login#1]
After installing the module, I am getting this when trying to log into the backend of magento:

1 exception(s):
Exception #0 (OutOfRangeException): Specified invalid parent id (ManishJoy_Core::core)

**Comment by manishjoy** [comment]
You need to install the core module for this one. Install this https://github.com/manishjoy/manishjoy-core

After that, everything will run smoothly

**Comment by tantuohy** [comment]
That works!
